/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import cliente.Cliente;
import cliente.Documento;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Allan Pereira da Silva
 */
public class ExibirDocumento extends javax.swing.JFrame {

    /**
     * Creates new form ExibirDocumento
     */
    public static ExibirDocumento exibirDoc;
    public ExibirDocumento() throws IOException, ClassNotFoundException {
        initComponents();
        Documento doc = BuscarDocumentos.docSelecionado;
        this.nomeProprietario.setText(doc.getProprietario()); 
        this.numeroCPF.setText(doc.getCpf_proprietario());
        this.valor.setText(String.valueOf(doc.getValorDoc()));
        Cliente cliente = new Cliente();
        cliente.cliente(TelaInicial.ipAux, TelaInicial.portaAux);
        System.out.println("iniciou cliente");
        String decod = cliente.decodificarTextoDoc(doc.getTexto());
        this.textoDocumento.setText(decod);
        cliente.sair();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeProprietario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroCPF = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDocumento = new javax.swing.JTextPane();
        voltar = new javax.swing.JButton();
        transferir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exibição de Documento");
        setResizable(false);

        jLabel1.setText("Proprietário :");

        nomeProprietario.setText("(Nome)");

        jLabel3.setText("CPF:");

        numeroCPF.setText("(NumeroCPF)");

        jLabel2.setText("Documento:");

        textoDocumento.setBorder(new javax.swing.border.MatteBorder(null));
        textoDocumento.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        textoDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textoDocumento.setEnabled(false);
        jScrollPane1.setViewportView(textoDocumento);

        voltar.setText("<");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        transferir.setText("Transferir");
        transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferirActionPerformed(evt);
            }
        });

        jLabel4.setText("R$:");

        valor.setText("(Valor)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(valor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(numeroCPF))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nomeProprietario))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(voltar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transferir))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeProprietario))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numeroCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(transferir))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void transferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferirActionPerformed
        TransferenciaDocumentos.telaTransferencia = new TransferenciaDocumentos();
        this.setVisible(false);
        TransferenciaDocumentos.telaTransferencia.setVisible(true);
    }//GEN-LAST:event_transferirActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        try {
            BuscarDocumentos.buscarDocs = new BuscarDocumentos();
            this.setVisible(false);
            BuscarDocumentos.buscarDocs.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ExibirDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ExibirDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_voltarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeProprietario;
    private javax.swing.JLabel numeroCPF;
    private javax.swing.JTextPane textoDocumento;
    private javax.swing.JButton transferir;
    private javax.swing.JLabel valor;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
