/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author karol
 */
public class MenuCidadao extends javax.swing.JFrame {

    /**
     * Creates new form MenuCidadao
     */
    public static MenuCidadao menucidadao;
    public MenuCidadao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarDocumentos = new javax.swing.JButton();
        verDocumentos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cadastrarDocumentos.setText("Cadastrar Documentos");
        cadastrarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarDocumentosActionPerformed(evt);
            }
        });

        verDocumentos.setText("Ver Documentos");
        verDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDocumentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verDocumentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cadastrarDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(verDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(cadastrarDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarDocumentosActionPerformed
        CadastroDocumentos.cadastro_documentos = new CadastroDocumentos();
        this.setVisible(false);
        menucidadao = null;
        CadastroDocumentos.cadastro_documentos.setVisible(true);
    }//GEN-LAST:event_cadastrarDocumentosActionPerformed

    private void verDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDocumentosActionPerformed
        
        try {
            BuscarDocumentos.buscarDocs = new BuscarDocumentos();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(MenuCidadao.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.setVisible(false);
            menucidadao = null;
            BuscarDocumentos.buscarDocs.setVisible(true);
        
    }//GEN-LAST:event_verDocumentosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarDocumentos;
    private javax.swing.JButton verDocumentos;
    // End of variables declaration//GEN-END:variables
}
